version: '3'
services:
  app:
    image: sloopstash/app:v1
    command: "/usr/bin/supervisord -c /etc/supervisord.conf"
    ports:
      - "8080:80"
    volumes:
      - /opt/kickstart-docker/app:/opt/app
      - /opt/kickstart-docker/nginx/conf/main.conf:/etc/nginx/nginx.conf
      - /opt/kickstart-docker/nginx/conf/app.conf:/etc/nginx/conf.d/app.conf
      - /opt/kickstart-docker/supervisor/conf/main.conf:/etc/supervisord.conf
      - /opt/kickstart-docker/supervisor/conf/app.ini:/etc/supervisord.d/app.ini
      - /opt/kickstart-docker/supervisor/conf/nginx.ini:/etc/supervisord.d/nginx.ini
    depends_on:
      - redis
    networks:
      - crm-net
    deploy:
      mode: replicated
      replicas: 5
  redis:
    image: sloopstash/redis:v1
    command: "/usr/bin/supervisord -c /etc/supervisord.conf"
    volumes:
      - /opt/kickstart-docker/redis/data:/opt/redis/data
      - /opt/kickstart-docker/redis/log:/opt/redis/log
      - /opt/kickstart-docker/redis/conf/main.conf:/opt/redis/conf/redis.conf
      - /opt/kickstart-docker/supervisor/conf/main.conf:/etc/supervisord.conf
      - /opt/kickstart-docker/supervisor/conf/redis.ini:/etc/supervisord.d/redis.ini
    networks:
      - crm-net
networks:
  crm-net:
    external:
      name: crm-net
