apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      service: redis
  replicas: 1
  template:
    metadata:
      labels:
        service: redis
    spec:
      containers:
        - name: main
          image: sloopstash/redis:v1
          volumeMounts:
            - name: opt-redis-data
              mountPath: /opt/redis/data
            - name: opt-redis-log
              mountPath: /opt/redis/log
            - name: opt-redis-conf-redis-conf
              mountPath: /opt/redis/conf/redis.conf
            - name: etc-supervisord-conf
              mountPath: /etc/supervisord.conf
            - name: etc-supervisord-d-redis-ini
              mountPath: /etc/supervisord.d/redis.ini
          command:
            - "/usr/bin/supervisord"
            - "-c"
            - "/etc/supervisord.conf"
          ports:
            - containerPort: 6379
      volumes:
        - name: opt-redis-data
          hostPath:
            path: /opt/kickstart-docker/redis/data
            type: Directory
        - name: opt-redis-log
          hostPath:
            path: /opt/kickstart-docker/redis/log
            type: Directory
        - name: opt-redis-conf-redis-conf
          hostPath:
            path: /opt/kickstart-docker/redis/conf/main.conf
            type: File
        - name: etc-supervisord-conf
          hostPath:
            path: /opt/kickstart-docker/supervisor/conf/main.conf
            type: File
        - name: etc-supervisord-d-redis-ini
          hostPath:
            path: /opt/kickstart-docker/supervisor/conf/redis.ini
            type: File
